name: "Build server.zip"
description: "Build server.zip"

runs:
  using: "composite"
  steps:
    # Setup Node 22
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Install dependencies
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    # Install zip
    - name: Install zip
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y zip

    # Run build script
    - name: Run build script
      shell: bash
      run: |
        chmod +x ./scripts/build.sh
        npm run build