name: Deploy

on: 
    release:
        types: 
          #- created -> it will trigger on draft release
          - published


jobs:
    migrate_db:
      runs-on: ubuntu-latest
      # run when new release published on master branch
      if: github.event.release.target_commitish == 'master'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install dependency
          shell: bash
          env:
            NODE_ENV: ${{ secrets.NODE_ENV }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_MAX_CONNECTION: ${{ secrets.DB_MAX_CONNECTION }}
            DB_USE_SSL: ${{ secrets.DB_USE_SSL }}
            DB_SSL_CA_BASE64: ${{ secrets.DB_SSL_CA_BASE64 }}
          run: |
            npm install
            npm install -D
            npm run drizzle:prod:migrate


    deploy_storage_and_cdn:
        runs-on: ubuntu-latest
        # run when new release published on master branch
        if: github.event.release.target_commitish == 'master'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Confugure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init 
              working-directory: ./terraform

            - name: Terrafrom Apply
              run: terraform apply -auto-approve
              working-directory: ./terraform
              env: 
                TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
